name: flowers_heat_v1
net:
  _target_: flowers_gnn.models.flowers_mesh.FlowersMesh
  latent_dim: 256
  num_blocks: 4
  num_heads: 64
  k_interp: 3
  max_disp: 0.5
  n_fields: 1
  use_node_type: false
